# Generated by Django 6.0.5 on 2026-06-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
